#!/usr/bin/env playonlinux-bash
[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources"
export WINEPREFIX="/home/suporte4/.var/app/com.playonlinux.PlayOnLinux4/data/PlayOnLinux//wineprefix/bitvise"
export WINEDEBUG="-all"
cd "/home/suporte4/.var/app/com.playonlinux.PlayOnLinux4/data/PlayOnLinux//wineprefix/bitvise/drive_c/./Program Files/Bitvise SSH Client"
POL_Wine "BvSsh.exe" -glclstgs=Keypairs
